### ISSUE TITLE
SyntaxError: invalid character

### ISSUE THREAD

**Issue by bulletproof2k** [nils1323/sabnzbd-telegram-script#1]
Script returned exit code 1 and output " File "E:\DEV\scripts\[telegram.py](http://telegram.py/)", line 104 <title>sabnzbd-telegram-script/[telegram.py](http://telegram.py/) at main � nilshee/sabnzbd-telegram-script</title> ^ SyntaxError: invalid character '�' (U+00B7) "

**Comment by nilshee** [comment]
Should be working now. Updated the file to my currenty running version
